
build-components: ## Build components
	$(MAKE) -C cpx-auth
	$(MAKE) -C cpx-blank
	$(MAKE) -C cpx-cookie
	$(MAKE) -C cpx-filter
	$(MAKE) -C cpx-keycloak
	$(MAKE) -C cpx-newsdesk
	$(MAKE) -C cpx-operator-graph
	$(MAKE) -C cpx-query
	$(MAKE) -C cpx-reporter
	$(MAKE) -C cpx-result
	$(MAKE) -C cpx-state
	$(MAKE) -C cpx-tab-stream
	$(MAKE) -C cpx-target
	$(MAKE) -C cpx-url
	$(MAKE) -C cpx-user
	$(MAKE) -C cpx-websocket